### PR TITLE
Fixed errors and mistakes in Romanian

### PR DESCRIPTION
**Pull request by Edward205**

### CODE REVIEW

**Comment by ProbablePrime** [comment]
#675 Was merged which looked to have even more updates, Edward please take a look through your changes and see if you can reconcile them with #675

**Comment by Edward205** [comment]
Changes from #675 are good corrections and include my corrections as well. It's okay to merge #675 instead of mine.

**Comment by Edward205** [comment]
You should update the README to include Romanian with a status of 100% complete.

**Comment by ProbablePrime** [comment]
Thank you Edward!

**Pull request closed without merging**
