### PR TITLE
zh-cn: full translation

### PR DESCRIPTION
**Pull request by StoneMoe**
Hi, Simplified Chinese native speaker here.
This PR contains:
1. Full Simplified Chinese(`zh-cn.json`) translation
2. Fix machine translating errors as many as possible for `zh-cn.json`
3. Formatting `zh-cn.json` to match key order and format with baseline `en.js`
4. Fix encoding issue in CleanJSON.py
5. Add convenient features for translating in CleanJSON.py
6. Fix incorrect `ISO 639-1` code in `localeCode` field

Future: will keep working on proofread, translating, and error fix for `zh-cn`.

### CODE REVIEW

**Comment by StoneMoe** [comment]
Thanks for response ProbablePrime :D
Hope better translation can happen soon since there is still a huge VR community can barely speak English.
And some of them start looking for a successor of VRChat recently.

I'll keep updating `zh-cn.json` for better translation quality.

**Comment by kazu0617** [comment]
> Thanks for your contribution @StoneMoe! The translation looks good.
> 
> As for the python changes, @kazu0617 and @Xqua would you mind reviewing the python changes as you two have been most active on the python script

I think no probrem in Python, but i think already fallback to en-us in neos client. it changes works for translators.

So after merge this pr, plz set actions for auto ci/cd to other language when en-US commit works.

**Comment by ProbablePrime** [comment]
It is still unclear to me which zh-cn translation is the more up to date one based on the comments here.

This is still low urgency as updates are still paused for the moment, but I'd like to get clarity on it when we can.

Thank you.

**Comment by StoneMoe** [comment]
> It is still unclear to me which zh-cn translation is the more up to date one based on the comments here.
> 
> This is still low urgency as updates are still paused for the moment, but I'd like to get clarity on it when we can.
> 
> Thank you.

Hi, great to see some progress is happening.
I'm contacting @metameqa via WeChat for further confirming now.

**Comment by StoneMoe** [comment]
@ProbablePrime after some discussion, @metameqa and I decided to merge this PR into #662
@metameqa will work on this these days
I will close this PR after everything is done.

**Comment by StoneMoe** [comment]
Closed by #662

**Pull request closed without merging**
