### PR TITLE
Adds a very uwu-ified locale based on en.json

### PR DESCRIPTION
**Pull request by Toxic-Cookie**

### CODE REVIEW

**Comment by Mawco** [comment]
honestly quite incredible

**Comment by EIA485** [comment]
those author names are not correctly region translated

**Comment by ProbablePrime** [comment]
Unfortunately, we're not going to be able to accept joke translations.

Once one makes it in, we'll have additional PRs lined up for various other Jokes, until it gets out of hand.

Feel free to use the joke translation via mods or direct download though.

**Comment by Toxic-Cookie** [comment]
> Unfortunately, we're not going to be able to accept joke translations.
> 
> Once one makes it in, we'll have additional PRs lined up for various other Jokes, until it gets out of hand.
> 
> Feel free to use the joke translation via mods or direct download though.

That's understandable. Thanks for the consideration.

**Pull request closed without merging**
