### PR TITLE
Norwegian V3

### PR DESCRIPTION
**Pull request by foxy-1423**
everything should be there, 
used a JSON translator tool in VSCODE
(https://marketplace.visualstudio.com/items?itemName=JeffJorczak.auto-translate-json)
(the tool needs a google Translator API key, i used some free credits i got a long time ago)
then ran the whole text throu the cleaner that was provided (thank god that's included thank you)

### CODE REVIEW

**Comment by foxy-1423** [comment]
and sorry about "re forking" neos locale, im really bad with github and made several mistakes before just redoing everyting

**Comment by foxy-1423** [comment]
I am Reborn, I changed my name to Revi.

**Comment by shadowpanther** [comment]
Ah, I'm sorry then

**Comment by foxy-1423** [comment]
no worries, cant expect new neos peeps to know my old nicknames

**Comment by Frooxius** [comment]
Is this purely a machine translation? Unfortunately we generally don't accept machine translated locales, due to the weirdness they tend to produce, especially for software UI strings.

**Pull request closed without merging**
